default_install_hook_types: [pre-commit, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: name-tests-test
      args:
        - "--pytest-test-first"
- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [python]
      args: [--fix]
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: hadolint
      name: Hadolint Dockerfiles
      entry: hadolint
      language: system
      types: ["dockerfile"]
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      stages: [push]
      language: system
